package top.cyanide.GRMS.dao;

import org.apache.ibatis.annotations.Param;
import top.cyanide.GRMS.pojo.Result;
import top.cyanide.GRMS.pojo.ResultExample;

import java.util.List;

/**
 * @author Bai
 */
public interface ResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    long countByExample(ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    int deleteByExample(ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    int insert(Result record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    int insertSelective(Result record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    List<Result> selectByExample(ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    Result selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") Result record, @Param("example") ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    int updateByExample(@Param("record") Result record, @Param("example") ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    int updateByPrimaryKeySelective(Result record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbg.generated Thu Sep 24 11:36:07 CST 2020
     */
    int updateByPrimaryKey(Result record);
}
