package top.cyanide.GRMS.pojo;

import java.util.ArrayList;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public OrderExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderIsNull() {
            addCriterion("add_to_cart_order is null");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderIsNotNull() {
            addCriterion("add_to_cart_order is not null");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderEqualTo(Integer value) {
            addCriterion("add_to_cart_order =", value, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderNotEqualTo(Integer value) {
            addCriterion("add_to_cart_order <>", value, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderGreaterThan(Integer value) {
            addCriterion("add_to_cart_order >", value, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("add_to_cart_order >=", value, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderLessThan(Integer value) {
            addCriterion("add_to_cart_order <", value, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderLessThanOrEqualTo(Integer value) {
            addCriterion("add_to_cart_order <=", value, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderIn(List<Integer> values) {
            addCriterion("add_to_cart_order in", values, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderNotIn(List<Integer> values) {
            addCriterion("add_to_cart_order not in", values, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderBetween(Integer value1, Integer value2) {
            addCriterion("add_to_cart_order between", value1, value2, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andAddToCartOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("add_to_cart_order not between", value1, value2, "addToCartOrder");
            return (Criteria) this;
        }

        public Criteria andReorderedIsNull() {
            addCriterion("reordered is null");
            return (Criteria) this;
        }

        public Criteria andReorderedIsNotNull() {
            addCriterion("reordered is not null");
            return (Criteria) this;
        }

        public Criteria andReorderedEqualTo(Integer value) {
            addCriterion("reordered =", value, "reordered");
            return (Criteria) this;
        }

        public Criteria andReorderedNotEqualTo(Integer value) {
            addCriterion("reordered <>", value, "reordered");
            return (Criteria) this;
        }

        public Criteria andReorderedGreaterThan(Integer value) {
            addCriterion("reordered >", value, "reordered");
            return (Criteria) this;
        }

        public Criteria andReorderedGreaterThanOrEqualTo(Integer value) {
            addCriterion("reordered >=", value, "reordered");
            return (Criteria) this;
        }

        public Criteria andReorderedLessThan(Integer value) {
            addCriterion("reordered <", value, "reordered");
            return (Criteria) this;
        }

        public Criteria andReorderedLessThanOrEqualTo(Integer value) {
            addCriterion("reordered <=", value, "reordered");
            return (Criteria) this;
        }

        public Criteria andReorderedIn(List<Integer> values) {
            addCriterion("reordered in", values, "reordered");
            return (Criteria) this;
        }

        public Criteria andReorderedNotIn(List<Integer> values) {
            addCriterion("reordered not in", values, "reordered");
            return (Criteria) this;
        }

        public Criteria andReorderedBetween(Integer value1, Integer value2) {
            addCriterion("reordered between", value1, value2, "reordered");
            return (Criteria) this;
        }

        public Criteria andReorderedNotBetween(Integer value1, Integer value2) {
            addCriterion("reordered not between", value1, value2, "reordered");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNull() {
            addCriterion("order_number is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNotNull() {
            addCriterion("order_number is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberEqualTo(Integer value) {
            addCriterion("order_number =", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotEqualTo(Integer value) {
            addCriterion("order_number <>", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThan(Integer value) {
            addCriterion("order_number >", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_number >=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThan(Integer value) {
            addCriterion("order_number <", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThanOrEqualTo(Integer value) {
            addCriterion("order_number <=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIn(List<Integer> values) {
            addCriterion("order_number in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotIn(List<Integer> values) {
            addCriterion("order_number not in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberBetween(Integer value1, Integer value2) {
            addCriterion("order_number between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("order_number not between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderDowIsNull() {
            addCriterion("order_dow is null");
            return (Criteria) this;
        }

        public Criteria andOrderDowIsNotNull() {
            addCriterion("order_dow is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDowEqualTo(Integer value) {
            addCriterion("order_dow =", value, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderDowNotEqualTo(Integer value) {
            addCriterion("order_dow <>", value, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderDowGreaterThan(Integer value) {
            addCriterion("order_dow >", value, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderDowGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_dow >=", value, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderDowLessThan(Integer value) {
            addCriterion("order_dow <", value, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderDowLessThanOrEqualTo(Integer value) {
            addCriterion("order_dow <=", value, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderDowIn(List<Integer> values) {
            addCriterion("order_dow in", values, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderDowNotIn(List<Integer> values) {
            addCriterion("order_dow not in", values, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderDowBetween(Integer value1, Integer value2) {
            addCriterion("order_dow between", value1, value2, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderDowNotBetween(Integer value1, Integer value2) {
            addCriterion("order_dow not between", value1, value2, "orderDow");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayIsNull() {
            addCriterion("order_hour_of_day is null");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayIsNotNull() {
            addCriterion("order_hour_of_day is not null");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayEqualTo(Integer value) {
            addCriterion("order_hour_of_day =", value, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayNotEqualTo(Integer value) {
            addCriterion("order_hour_of_day <>", value, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayGreaterThan(Integer value) {
            addCriterion("order_hour_of_day >", value, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_hour_of_day >=", value, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayLessThan(Integer value) {
            addCriterion("order_hour_of_day <", value, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayLessThanOrEqualTo(Integer value) {
            addCriterion("order_hour_of_day <=", value, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayIn(List<Integer> values) {
            addCriterion("order_hour_of_day in", values, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayNotIn(List<Integer> values) {
            addCriterion("order_hour_of_day not in", values, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayBetween(Integer value1, Integer value2) {
            addCriterion("order_hour_of_day between", value1, value2, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andOrderHourOfDayNotBetween(Integer value1, Integer value2) {
            addCriterion("order_hour_of_day not between", value1, value2, "orderHourOfDay");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderIsNull() {
            addCriterion("days_since_prior_order is null");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderIsNotNull() {
            addCriterion("days_since_prior_order is not null");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderEqualTo(Float value) {
            addCriterion("days_since_prior_order =", value, "daysSincePriorOrder");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderNotEqualTo(Float value) {
            addCriterion("days_since_prior_order <>", value, "daysSincePriorOrder");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderGreaterThan(Float value) {
            addCriterion("days_since_prior_order >", value, "daysSincePriorOrder");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderGreaterThanOrEqualTo(Float value) {
            addCriterion("days_since_prior_order >=", value, "daysSincePriorOrder");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderLessThan(Float value) {
            addCriterion("days_since_prior_order <", value, "daysSincePriorOrder");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderLessThanOrEqualTo(Float value) {
            addCriterion("days_since_prior_order <=", value, "daysSincePriorOrder");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderIn(List<Float> values) {
            addCriterion("days_since_prior_order in", values, "daysSincePriorOrder");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderNotIn(List<Float> values) {
            addCriterion("days_since_prior_order not in", values, "daysSincePriorOrder");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderBetween(Float value1, Float value2) {
            addCriterion("days_since_prior_order between", value1, value2, "daysSincePriorOrder");
            return (Criteria) this;
        }

        public Criteria andDaysSincePriorOrderNotBetween(Float value1, Float value2) {
            addCriterion("days_since_prior_order not between", value1, value2, "daysSincePriorOrder");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 23 17:42:50 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 23 17:42:50 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}